pipeline {
    agent {
        docker {
            image 'maven:3.3.3'
            args '-v //C:/Users/afant/.m2:/root/.m2'
        }
    }

    stages {
        stage('Static Inspect') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('Compile and Package') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('Unit Test') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('Component Test') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('Smoke/Acceptance Test') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('Deploy to Testing Env') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('Performance Test') {
            steps {
                bat 'mvn clean'
            }
        }
        stage('Deploy to Production Env') {
            steps {
                bat 'mvn clean'
            }
        }
    }
}